global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '23521250@gm.uit.edu.vn' 
  smtp_auth_username: '23521250@gm.uit.edu.vn'
  smtp_auth_password: 'phzk ftnw tgtf kfmu'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-receiver'

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'bcmquan@gmail.com'
        send_resolved: true
    webhook_configs:
      - url: 'http://host.docker.internal:5000/webhook'
        send_resolved: false